'use strict';

const assert = require('node:assert/strict');
const { readFile } = require('node:fs/promises');
const path = require('node:path');
const test = require('node:test');

const {
  __panelAccessCutoverRuntimeTest: helpers,
} = require('../dist/system/2026-08-25-004-panel-access-federation-cutover-runtime');

const cutoverId = '11111111-2222-4333-8444-555555555555';
const managedConfig = [
  '# Generated by meowbox panel-access manager. DO NOT EDIT MANUALLY.',
  `# federation-cutover: ${cutoverId}`,
  'server { listen 443 ssl; }',
  '',
].join('\n');

function artifacts(overrides = {}) {
  return {
    configKind: 'missing',
    configContent: null,
    linkKind: 'missing',
    linkTarget: null,
    journalNames: [],
    ...overrides,
  };
}

test('SYS-03 Panel Access candidate runtime is absent or one fully bound managed pair', () => {
  assert.equal(helpers.validateCandidateArtifacts(artifacts()), null);
  assert.equal(helpers.validateCandidateArtifacts(artifacts({
    configKind: 'file',
    configContent: managedConfig,
    linkKind: 'symlink',
    linkTarget: helpers.candidateConfig,
    journalNames: [`${cutoverId}.json`],
  })), cutoverId);

  assert.throws(() => helpers.validateCandidateArtifacts(artifacts({
    configKind: 'file',
    configContent: managedConfig,
  })), /pair is incomplete/);
  assert.throws(() => helpers.validateCandidateArtifacts(artifacts({
    configKind: 'file',
    configContent: managedConfig,
    linkKind: 'symlink',
    linkTarget: '/tmp/unmanaged',
    journalNames: [`${cutoverId}.json`],
  })), /not managed/);
  assert.throws(() => helpers.validateCandidateArtifacts(artifacts({
    configKind: 'file',
    configContent: 'server {}\n',
    linkKind: 'symlink',
    linkTarget: helpers.candidateConfig,
    journalNames: [`${cutoverId}.json`],
  })), /no valid cutover marker/);
  assert.throws(() => helpers.validateCandidateArtifacts(artifacts({
    configKind: 'file',
    configContent: managedConfig,
    linkKind: 'symlink',
    linkTarget: helpers.candidateConfig,
  })), /no matching durable journal/);
});

test('SYS-01 Panel Access cutover journals live under persistent state', () => {
  assert.equal(
    helpers.cutoverStateDirectory('/opt/meowbox/state'),
    '/opt/meowbox/state/data/panel-access-cutovers',
  );
});

test('SYS-03 agent cutover contract validates before Nginx reload and keeps recovery state', async () => {
  const root = path.resolve(__dirname, '..', '..');
  const [agent, target, schema] = await Promise.all([
    readFile(path.join(root, 'agent/src/panel-access/panel-access.manager.ts'), 'utf8'),
    readFile(path.join(root, 'api/src/panel-access/panel-access-cutover-target.service.ts'), 'utf8'),
    readFile(path.join(root, 'api/prisma/schema.prisma'), 'utf8'),
  ]);
  assert.match(agent, /CUTOVER_STATE_DIR = '\/opt\/meowbox\/state\/data\/panel-access-cutovers'/);
  assert.match(agent, /execute\('nginx', \['-t'\]/);
  assert.match(agent, /writeAtomicFile\([\s\S]*0o600/);
  assert.match(agent, /state: 'FINALIZED'/);
  assert.match(agent, /state: 'ROLLED_BACK'/);
  assert.match(target, /UNKNOWN_RECOVERY_REQUIRED|NEEDS_ATTENTION/);
  assert.match(schema, /model RemoteEndpointCutover/);
  assert.doesNotMatch(agent, /rejectUnauthorized\s*:\s*false/);
});
