'use strict';

const assert = require('node:assert/strict');
const test = require('node:test');

const {
  __panelAccessStandardHttpsTest,
} = require('../dist/system/2026-09-09-001-panel-access-standard-https');

const { parsePanelAccess, parsePanelPort, patchPanelNginx } = __panelAccessStandardHttpsTest;

const activeConfig = `# Generated by meowbox panel-access manager. DO NOT EDIT MANUALLY.
server {
    listen 80;
    listen [::]:80;
    server_name panel.example.test;
    location / {
        return 301 https://$host:11862$request_uri;
    }
}

server {
    listen 11862 ssl;
    listen [::]:11862 ssl;
    server_name panel.example.test _;
    ssl_certificate /etc/letsencrypt/live/panel.example.test/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/panel.example.test/privkey.pem;
    # Security headers
    # API proxy
    location /api/ { proxy_pass http://meowbox_api; }
}
`;

const settings = {
  domain: 'panel.example.test',
  certMode: 'LE',
  denyIpAccess: false,
};

test('panel domain migration adds standard HTTPS and removes the port from redirects', () => {
  const patched = patchPanelNginx(activeConfig, settings, 11862);
  assert.match(patched, /listen 443 ssl;/);
  assert.match(patched, /listen \[::\]:443 ssl;/);
  assert.match(patched, /listen 11862 ssl;/);
  assert.match(patched, /return 301 https:\/\/\$host\$request_uri;/);
  assert.match(patched, /location = \/api\/panel-access\/cert\/le/);
  assert.match(patched, /proxy_read_timeout 360s/);
  assert.doesNotMatch(patched, /https:\/\/\$host:11862/);
  assert.equal(patchPanelNginx(patched, settings, 11862), patched);
});

test('denyIpAccess removes the panel application listener from the recovery port', () => {
  const patched = patchPanelNginx(
    activeConfig.replace('server_name panel.example.test _;', 'server_name panel.example.test;'),
    { ...settings, denyIpAccess: true },
    11862,
  );
  const mainHeader = patched.slice(
    patched.lastIndexOf('\nserver {', patched.indexOf('    # Security headers')),
    patched.indexOf('    # Security headers'),
  );
  assert.match(mainHeader, /listen 443 ssl;/);
  assert.doesNotMatch(mainHeader, /11862/);
});

test('migration parsers reject invalid state and keep IP-only configs unchanged', () => {
  assert.equal(parsePanelPort('PANEL_PORT="18443"\n'), 18443);
  assert.throws(() => parsePanelPort('PANEL_PORT=70000\n'), /PANEL_PORT is invalid/);
  assert.throws(
    () => parsePanelAccess('{"domain":"bad domain","certMode":"LE","denyIpAccess":false}'),
    /domain is invalid/,
  );
  assert.equal(
    patchPanelNginx(activeConfig, { domain: null, certMode: 'SELFSIGNED', denyIpAccess: false }, 11862),
    activeConfig,
  );
});
