/**
 * Bootstrap PROXY_TOKEN для существующих установок.
 *
 * Что делает:
 *   1. Проверяет state/.env (или legacy .env) на наличие PROXY_TOKEN.
 *   2. Если не задан — генерирует 64-hex токен и дописывает в .env.
 *   3. chmod 600 .env (закрываем mode даже если был 644).
 *
 * Зачем:
 *   - Старые установки (до 0.4.0) не имели PROXY_TOKEN — slave-режим не работал.
 *   - Теперь по умолчанию каждая панель готова принимать прокси-запросы.
 *   - Пользователь зайдёт в .env, скопирует токен и добавит сервер на master-панели.
 *
 * Идемпотентно: повторный запуск ничего не делает, если PROXY_TOKEN уже задан.
 */

import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { randomBytes } from 'node:crypto';

import type { SystemMigration } from './_types';

function findEnvFile(): string {
  const candidates = ['/opt/meowbox/state/.env', '/opt/meowbox/.env'];
  for (const p of candidates) {
    try {
      // sync stat ok — это короткая операция в миграции.
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const fsSync = require('node:fs') as typeof import('node:fs');
      if (fsSync.existsSync(p)) return p;
    } catch { /* */ }
  }
  return candidates[0];
}

const migration: SystemMigration = {
  id: '2026-04-30-003-proxy-token-bootstrap',
  description: 'Генерирует PROXY_TOKEN в .env если не задан (bootstrap slave-режима)',

  async up(ctx) {
    const envFile = findEnvFile();

    if (!(await ctx.exists(envFile))) {
      ctx.log(`SKIP: .env не найден (${envFile}) — install.sh ещё не отработал`);
      return;
    }

    const content = await ctx.readFile(envFile);

    // Регулярка: PROXY_TOKEN="не_пустое_значение" в любом регистре, не закомментировано.
    const hasValid = /^[ \t]*PROXY_TOKEN[ \t]*=[ \t]*"[^"\n]+"/m.test(content);
    if (hasValid) {
      ctx.log(`OK: PROXY_TOKEN уже задан в ${envFile}`);
      // Закроем chmod на всякий случай — могли оставить 644 после ручных правок.
      await fs.chmod(envFile, 0o600).catch(() => {});
      return;
    }

    // Генерируем 64-hex токен (256 бит).
    const token = randomBytes(32).toString('hex');

    // Удаляем закомментированную PROXY_TOKEN=CHANGE_ME заглушку если есть,
    // чтобы не плодить дубли.
    let newContent = content.replace(/^[ \t]*#[ \t]*PROXY_TOKEN=.*$\n?/gim, '');
    if (!newContent.endsWith('\n')) newContent += '\n';
    newContent += `\n# PROXY_TOKEN: server-to-server токен для master→slave прокси (auto-generated by migration)\nPROXY_TOKEN="${token}"\n`;

    if (ctx.dryRun) {
      ctx.log(`would append PROXY_TOKEN to ${envFile}`);
      return;
    }

    // Бэкап на случай если кто-то параллельно правил env.
    const backup = `${envFile}.bak.${Date.now()}`;
    await fs.copyFile(envFile, backup);

    await fs.writeFile(envFile, newContent, 'utf8');
    await fs.chmod(envFile, 0o600);

    ctx.log(`OK: PROXY_TOKEN добавлен в ${envFile} (бэкап: ${path.basename(backup)})`);
    ctx.log(`После рестарта meowbox-api панель будет принимать прокси-запросы с этим токеном.`);
  },
};

export default migration;
