import { createHash } from 'node:crypto';
import {
  chmod,
  chown,
  lstat,
  mkdir,
  readlink,
  readdir,
  stat,
} from 'node:fs/promises';
import * as path from 'node:path';

import type { MigrationContext, MigrationPlan, SystemMigration } from './_types';

const MIGRATION_ID = '2026-08-25-004-panel-access-federation-cutover-runtime';
const PANEL_NGINX_CONFIG = '/etc/nginx/sites-available/meowbox-panel';
const CANDIDATE_CONFIG = '/etc/nginx/sites-available/meowbox-panel-candidate';
const CANDIDATE_LINK = '/etc/nginx/sites-enabled/meowbox-panel-candidate';
const CUTOVER_ID_SOURCE = '[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}';
const CUTOVER_FILE = new RegExp(`^(${CUTOVER_ID_SOURCE})\\.json$`);
const CUTOVER_MARKER = new RegExp(
  `^# Generated by meowbox panel-access manager\\. DO NOT EDIT MANUALLY\\.\\n# federation-cutover: (${CUTOVER_ID_SOURCE})\\n`,
);

type ArtifactKind = 'missing' | 'file' | 'symlink' | 'other';

interface CandidateArtifacts {
  configKind: ArtifactKind;
  configContent: string | null;
  linkKind: ArtifactKind;
  linkTarget: string | null;
  journalNames: string[];
}

interface Inspection {
  runtimeDirectory: string;
  directoryMissing: boolean;
  directoryMode: number | null;
  directoryOwnerMatches: boolean | null;
  insecureJournalCount: number;
  journalCount: number;
  activeCandidateId: string | null;
}

function cutoverStateDirectory(stateDir: string): string {
  return path.join(stateDir, 'data', 'panel-access-cutovers');
}

function validateCandidateArtifacts(artifacts: CandidateArtifacts): string | null {
  const configExists = artifacts.configKind !== 'missing';
  const linkExists = artifacts.linkKind !== 'missing';
  if (configExists !== linkExists) {
    throw new Error('Panel Access candidate Nginx config/link pair is incomplete');
  }
  if (!configExists) return null;
  if (artifacts.configKind !== 'file') {
    throw new Error('Panel Access candidate Nginx config must be a regular file');
  }
  if (artifacts.linkKind !== 'symlink' || artifacts.linkTarget !== CANDIDATE_CONFIG) {
    throw new Error('Panel Access candidate Nginx link is not managed by Meowbox');
  }
  const match = CUTOVER_MARKER.exec(artifacts.configContent ?? '');
  if (!match) throw new Error('Panel Access candidate Nginx config has no valid cutover marker');
  const cutoverId = match[1];
  if (!artifacts.journalNames.includes(`${cutoverId}.json`)) {
    throw new Error('Panel Access candidate Nginx config has no matching durable journal');
  }
  return cutoverId;
}

async function artifactKind(file: string): Promise<ArtifactKind> {
  try {
    const value = await lstat(file);
    if (value.isFile()) return 'file';
    if (value.isSymbolicLink()) return 'symlink';
    return 'other';
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return 'missing';
    throw error;
  }
}

async function journalNames(directory: string): Promise<string[]> {
  try {
    const names = await readdir(directory);
    for (const name of names) {
      if (!CUTOVER_FILE.test(name)) {
        throw new Error(`Unexpected Panel Access cutover runtime entry: ${name}`);
      }
      const metadata = await lstat(path.join(directory, name));
      if (!metadata.isFile()) {
        throw new Error(`Panel Access cutover journal must be a regular file: ${name}`);
      }
    }
    return names.sort();
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return [];
    throw error;
  }
}

async function inspect(ctx: MigrationContext): Promise<Inspection> {
  const dataDirectory = path.join(ctx.config.stateDir, 'data');
  if (!(await ctx.exists(dataDirectory))) {
    throw new Error(`Panel state data directory is missing: ${dataDirectory}`);
  }
  if (!(await ctx.exists(PANEL_NGINX_CONFIG))) {
    throw new Error(`Nginx panel config is missing: ${PANEL_NGINX_CONFIG}`);
  }

  const reference = await stat(dataDirectory);
  const runtimeDirectory = cutoverStateDirectory(ctx.config.stateDir);
  const runtimeKind = await artifactKind(runtimeDirectory);
  if (!(['missing', 'other'] as ArtifactKind[]).includes(runtimeKind)) {
    throw new Error(`Panel Access cutover runtime path is not a directory: ${runtimeDirectory}`);
  }
  let directoryMode: number | null = null;
  let directoryOwnerMatches: boolean | null = null;
  if (runtimeKind === 'other') {
    const metadata = await stat(runtimeDirectory);
    if (!metadata.isDirectory()) {
      throw new Error(`Panel Access cutover runtime path is not a directory: ${runtimeDirectory}`);
    }
    directoryMode = metadata.mode & 0o777;
    directoryOwnerMatches = metadata.uid === reference.uid && metadata.gid === reference.gid;
  }

  const journals = await journalNames(runtimeDirectory);
  let insecureJournalCount = 0;
  for (const name of journals) {
    const metadata = await lstat(path.join(runtimeDirectory, name));
    if (
      (metadata.mode & 0o777) !== 0o600 ||
      metadata.uid !== reference.uid ||
      metadata.gid !== reference.gid
    ) insecureJournalCount += 1;
  }

  const configKind = await artifactKind(CANDIDATE_CONFIG);
  const linkKind = await artifactKind(CANDIDATE_LINK);
  const configContent = configKind === 'file' ? await ctx.readFile(CANDIDATE_CONFIG) : null;
  if (configContent && Buffer.byteLength(configContent, 'utf8') > 512 * 1024) {
    throw new Error('Panel Access candidate Nginx config is oversized');
  }
  const linkTarget = linkKind === 'symlink' ? await readlink(CANDIDATE_LINK) : null;
  const activeCandidateId = validateCandidateArtifacts({
    configKind,
    configContent,
    linkKind,
    linkTarget,
    journalNames: journals,
  });

  return {
    runtimeDirectory,
    directoryMissing: runtimeKind === 'missing',
    directoryMode,
    directoryOwnerMatches,
    insecureJournalCount,
    journalCount: journals.length,
    activeCandidateId,
  };
}

function buildPlan(state: Inspection): MigrationPlan {
  const details = {
    directoryMissing: state.directoryMissing,
    directoryMode: state.directoryMode,
    directoryOwnerMatches: state.directoryOwnerMatches,
    insecureJournalCount: state.insecureJournalCount,
    journalCount: state.journalCount,
    activeCandidate: state.activeCandidateId !== null,
  };
  return {
    summary: 'Install fail-closed Panel Access endpoint-cutover runtime',
    fingerprint: createHash('sha256').update(JSON.stringify(details)).digest('hex'),
    details,
  };
}

async function ensureRuntime(ctx: MigrationContext): Promise<void> {
  const dataDirectory = path.join(ctx.config.stateDir, 'data');
  const reference = await stat(dataDirectory);
  const runtimeDirectory = cutoverStateDirectory(ctx.config.stateDir);
  await mkdir(runtimeDirectory, { recursive: true, mode: 0o700 });
  await chown(runtimeDirectory, reference.uid, reference.gid);
  await chmod(runtimeDirectory, 0o700);
  for (const name of await journalNames(runtimeDirectory)) {
    const file = path.join(runtimeDirectory, name);
    await chown(file, reference.uid, reference.gid);
    await chmod(file, 0o600);
  }
}

const migration: SystemMigration = {
  id: MIGRATION_ID,
  description: 'Install secure durable runtime for distributed Panel Access endpoint cutovers',

  async preflight(ctx) {
    try {
      await inspect(ctx);
      return { ok: true };
    } catch (error) {
      return { ok: false, reason: (error as Error).message };
    }
  },

  async plan(ctx) {
    return buildPlan(await inspect(ctx));
  },

  async up(ctx) {
    await inspect(ctx);
    await ensureRuntime(ctx);
    await ctx.exec.run('nginx', ['-t']);
    const final = await inspect(ctx);
    if (
      final.directoryMissing ||
      final.directoryMode !== 0o700 ||
      final.directoryOwnerMatches !== true ||
      final.insecureJournalCount !== 0
    ) throw new Error('Panel Access cutover runtime final verification failed');
    ctx.log('OK: Panel Access cutover runtime installed; active endpoint was not changed');
  },
};

export const __panelAccessCutoverRuntimeTest = {
  candidateConfig: CANDIDATE_CONFIG,
  cutoverStateDirectory,
  validateCandidateArtifacts,
};

export default migration;
