import {
  DASHBOARD_CONTRACT_VERSION,
  type DashboardOverview,
  type DashboardSourceState,
} from './dashboard';

const observedAt = '2026-08-23T08:00:00.000Z';

const okSource: DashboardSourceState = {
  availability: 'OK',
  observedAt,
  staleAfterSeconds: 45,
  message: null,
};

export const dashboardAdminHealthyFixture: DashboardOverview = {
  contractVersion: DASHBOARD_CONTRACT_VERSION,
  generatedAt: observedAt,
  role: 'ADMIN',
  server: {
    source: okSource,
    id: 'main',
    displayName: 'Этот сервер',
    connectionState: 'ONLINE',
    hostname: 'meowbox.local',
    uptimeSeconds: 86400,
    agentState: 'CONNECTED',
    agentLastSeenAt: observedAt,
    installedVersion: 'v1.0.0',
    updateState: 'CURRENT',
    targetVersion: null,
  },
  overall: {
    state: 'HEALTHY',
    criticalCount: 0,
    warningCount: 0,
    infoCount: 0,
    degradedSourceCount: 0,
  },
  problems: {
    total: 0,
    critical: 0,
    warning: 0,
    info: 0,
    truncated: false,
    items: [],
  },
  resources: {
    source: okSource,
    collectedAt: observedAt,
    cpuUsagePercent: 12.5,
    cpuCores: 4,
    memoryUsedBytes: 2147483648,
    memoryTotalBytes: 4294967296,
    memoryUsagePercent: 50,
    loadAverage: [0.3, 0.25, 0.2],
    disks: [{
      mountPoint: '/',
      totalBytes: 107374182400,
      usedBytes: 32212254720,
      availableBytes: 75161927680,
      usagePercent: 30,
    }],
    network: { rxBytesPerSecond: 2048, txBytesPerSecond: 1024 },
    history: { cpu: [], memory: [], rootDisk: [] },
  },
  sites: {
    source: okSource,
    total: 1,
    running: 1,
    error: 0,
    deploying: 0,
    managedDomains: 1,
    items: [{
      id: 'site-1',
      displayName: 'Example',
      primaryDomain: 'example.test',
      status: 'RUNNING',
      affectedDomainCount: 0,
      availabilityPercent: 100,
      availabilitySampleCount: 12,
      activeOperation: false,
      updatedAt: observedAt,
    }],
  },
  runtime: {
    source: okSource,
    activeOperations: [],
    services: [],
    diagnosticsPartial: false,
  },
  protection: {
    source: okSource,
    backup: {
      eligibleSiteCount: 1,
      protectedSiteCount: 1,
      latestSuccessfulAt: observedAt,
      failedLast24Hours: 0,
      overdueScheduleCount: 0,
      activeCount: 0,
      repositoryCheckState: 'UNCONFIGURED',
      repositoryCheckedAt: null,
    },
    ssl: {
      valid: 1,
      expiring: 0,
      expiredOrError: 0,
      nearestExpiryDomain: 'example.test',
      nearestExpiryDays: 80,
      exceptions: [],
    },
  },
  security: {
    source: okSource,
    failedLoginsLast24Hours: 0,
    activeSessionCount: 1,
    lastSuccessfulLoginAt: observedAt,
    lastSuccessfulLoginActor: 'operator',
    firewallSummary: null,
  },
  activity: { source: okSource, items: [] },
  capabilities: {
    overviewV1: true,
    nginxValidation: 'SUPPORTED',
    nginxDrift: 'SUPPORTED',
    dnsDrift: 'UNSUPPORTED',
    pm2Diagnostics: 'SUPPORTED',
    updateReadiness: 'UNSUPPORTED',
  },
};

export const dashboardManagerEmptyFixture: DashboardOverview = {
  ...dashboardAdminHealthyFixture,
  role: 'MANAGER',
  overall: {
    state: 'UNKNOWN',
    criticalCount: 0,
    warningCount: 0,
    infoCount: 0,
    degradedSourceCount: 2,
  },
  server: {
    ...dashboardAdminHealthyFixture.server,
    hostname: null,
    uptimeSeconds: null,
    agentState: 'UNKNOWN',
    agentLastSeenAt: null,
    installedVersion: null,
    updateState: 'UNSUPPORTED',
  },
  resources: {
    ...dashboardAdminHealthyFixture.resources,
    source: {
      availability: 'UNSUPPORTED',
      observedAt: null,
      staleAfterSeconds: null,
      message: 'Метрики сервера доступны только администратору',
    },
    collectedAt: null,
    cpuUsagePercent: null,
    cpuCores: null,
    memoryUsedBytes: null,
    memoryTotalBytes: null,
    memoryUsagePercent: null,
    loadAverage: null,
    disks: [],
    network: null,
  },
  sites: {
    source: okSource,
    total: 0,
    running: 0,
    error: 0,
    deploying: 0,
    managedDomains: 0,
    items: [],
  },
  runtime: {
    source: okSource,
    activeOperations: [],
    services: [],
    diagnosticsPartial: false,
  },
  protection: {
    ...dashboardAdminHealthyFixture.protection,
    backup: {
      eligibleSiteCount: 0,
      protectedSiteCount: 0,
      latestSuccessfulAt: null,
      failedLast24Hours: 0,
      overdueScheduleCount: 0,
      activeCount: 0,
      repositoryCheckState: 'UNCONFIGURED',
      repositoryCheckedAt: null,
    },
    ssl: {
      valid: 0,
      expiring: 0,
      expiredOrError: 0,
      nearestExpiryDomain: null,
      nearestExpiryDays: null,
      exceptions: [],
    },
  },
  security: null,
  activity: {
    source: {
      availability: 'UNSUPPORTED',
      observedAt: null,
      staleAfterSeconds: null,
      message: 'Журнал недоступен для этой роли',
    },
    items: [],
  },
  capabilities: {
    overviewV1: true,
    nginxValidation: 'UNSUPPORTED',
    nginxDrift: 'UNSUPPORTED',
    dnsDrift: 'UNSUPPORTED',
    pm2Diagnostics: 'UNSUPPORTED',
    updateReadiness: 'UNSUPPORTED',
  },
};

export const dashboardPartialFixture: DashboardOverview = {
  ...dashboardAdminHealthyFixture,
  overall: {
    state: 'UNKNOWN',
    criticalCount: 0,
    warningCount: 0,
    infoCount: 0,
    degradedSourceCount: 1,
  },
  resources: {
    ...dashboardAdminHealthyFixture.resources,
    source: {
      availability: 'UNAVAILABLE',
      observedAt: null,
      staleAfterSeconds: 45,
      message: 'Метрики временно недоступны',
    },
    collectedAt: null,
    cpuUsagePercent: null,
    cpuCores: null,
    memoryUsedBytes: null,
    memoryTotalBytes: null,
    memoryUsagePercent: null,
    loadAverage: null,
    disks: [],
    network: null,
  },
};

export const dashboardCriticalFixture: DashboardOverview = {
  ...dashboardAdminHealthyFixture,
  overall: {
    state: 'CRITICAL',
    criticalCount: 1,
    warningCount: 1,
    infoCount: 0,
    degradedSourceCount: 0,
  },
  problems: {
    total: 2,
    critical: 1,
    warning: 1,
    info: 0,
    truncated: false,
    items: [
      {
        id: 'DISK_USAGE_CRITICAL:SERVER:root',
        code: 'DISK_USAGE_CRITICAL',
        severity: 'CRITICAL',
        category: 'SYSTEM',
        title: 'Диск почти заполнен',
        summary: '/: занято 96.0%, свободно 1.0 GiB.',
        entity: { kind: 'SERVER', id: 'root', label: '/' },
        occurredAt: observedAt,
        observedAt,
        action: { kind: 'NAVIGATE', target: 'MONITORING', entityId: null, label: 'Открыть мониторинг' },
      },
      {
        id: 'BACKUP_COVERAGE_GAP:BACKUP:coverage',
        code: 'BACKUP_COVERAGE_GAP',
        severity: 'WARNING',
        category: 'BACKUP',
        title: 'Не все сайты защищены',
        summary: 'Без активного расписания: 1 сайт.',
        entity: { kind: 'BACKUP', id: 'coverage', label: 'Покрытие бэкапами' },
        occurredAt: null,
        observedAt,
        action: { kind: 'NAVIGATE', target: 'BACKUPS', entityId: null, label: 'Открыть бэкапы' },
      },
    ],
  },
};

export const dashboardLegacyFixture: DashboardOverview = {
  ...dashboardPartialFixture,
  server: {
    ...dashboardPartialFixture.server,
    source: {
      availability: 'UNSUPPORTED',
      observedAt: null,
      staleAfterSeconds: null,
      message: 'Выбранный сервер не поддерживает Dashboard Overview v1',
    },
    updateState: 'UNSUPPORTED',
  },
  capabilities: {
    overviewV1: false,
    nginxValidation: 'UNSUPPORTED',
    nginxDrift: 'UNSUPPORTED',
    dnsDrift: 'UNSUPPORTED',
    pm2Diagnostics: 'UNSUPPORTED',
    updateReadiness: 'UNSUPPORTED',
  },
};
