// ISO 3166-1 alpha-2 коды + читаемые названия (для UI на стороне API/web).
// Список достаточный — все суверенные государства + основные зависимые
// территории. Не все из них присутствуют в ipdeny/herrbischoff (например,
// микрогосударства AX, IM могут отсутствовать) — для таких agent просто
// вернёт ошибку при загрузке базы, и оператор увидит её в UI.
//
// Источник: ISO 3166-1 (RU-локализация — стандартные русские названия).

export const COUNTRIES: ReadonlyArray<{ code: string; name: string }> = [
  { code: 'AD', name: 'Андорра' },
  { code: 'AE', name: 'ОАЭ' },
  { code: 'AF', name: 'Афганистан' },
  { code: 'AG', name: 'Антигуа и Барбуда' },
  { code: 'AL', name: 'Албания' },
  { code: 'AM', name: 'Армения' },
  { code: 'AO', name: 'Ангола' },
  { code: 'AR', name: 'Аргентина' },
  { code: 'AT', name: 'Австрия' },
  { code: 'AU', name: 'Австралия' },
  { code: 'AW', name: 'Аруба' },
  { code: 'AZ', name: 'Азербайджан' },
  { code: 'BA', name: 'Босния и Герцеговина' },
  { code: 'BB', name: 'Барбадос' },
  { code: 'BD', name: 'Бангладеш' },
  { code: 'BE', name: 'Бельгия' },
  { code: 'BF', name: 'Буркина-Фасо' },
  { code: 'BG', name: 'Болгария' },
  { code: 'BH', name: 'Бахрейн' },
  { code: 'BI', name: 'Бурунди' },
  { code: 'BJ', name: 'Бенин' },
  { code: 'BN', name: 'Бруней' },
  { code: 'BO', name: 'Боливия' },
  { code: 'BR', name: 'Бразилия' },
  { code: 'BS', name: 'Багамы' },
  { code: 'BT', name: 'Бутан' },
  { code: 'BW', name: 'Ботсвана' },
  { code: 'BY', name: 'Беларусь' },
  { code: 'BZ', name: 'Белиз' },
  { code: 'CA', name: 'Канада' },
  { code: 'CD', name: 'ДР Конго' },
  { code: 'CF', name: 'ЦАР' },
  { code: 'CG', name: 'Республика Конго' },
  { code: 'CH', name: 'Швейцария' },
  { code: 'CI', name: 'Кот-д’Ивуар' },
  { code: 'CL', name: 'Чили' },
  { code: 'CM', name: 'Камерун' },
  { code: 'CN', name: 'Китай' },
  { code: 'CO', name: 'Колумбия' },
  { code: 'CR', name: 'Коста-Рика' },
  { code: 'CU', name: 'Куба' },
  { code: 'CV', name: 'Кабо-Верде' },
  { code: 'CY', name: 'Кипр' },
  { code: 'CZ', name: 'Чехия' },
  { code: 'DE', name: 'Германия' },
  { code: 'DJ', name: 'Джибути' },
  { code: 'DK', name: 'Дания' },
  { code: 'DM', name: 'Доминика' },
  { code: 'DO', name: 'Доминикана' },
  { code: 'DZ', name: 'Алжир' },
  { code: 'EC', name: 'Эквадор' },
  { code: 'EE', name: 'Эстония' },
  { code: 'EG', name: 'Египет' },
  { code: 'ER', name: 'Эритрея' },
  { code: 'ES', name: 'Испания' },
  { code: 'ET', name: 'Эфиопия' },
  { code: 'FI', name: 'Финляндия' },
  { code: 'FJ', name: 'Фиджи' },
  { code: 'FM', name: 'Микронезия' },
  { code: 'FR', name: 'Франция' },
  { code: 'GA', name: 'Габон' },
  { code: 'GB', name: 'Великобритания' },
  { code: 'GD', name: 'Гренада' },
  { code: 'GE', name: 'Грузия' },
  { code: 'GH', name: 'Гана' },
  { code: 'GM', name: 'Гамбия' },
  { code: 'GN', name: 'Гвинея' },
  { code: 'GQ', name: 'Экваториальная Гвинея' },
  { code: 'GR', name: 'Греция' },
  { code: 'GT', name: 'Гватемала' },
  { code: 'GW', name: 'Гвинея-Бисау' },
  { code: 'GY', name: 'Гайана' },
  { code: 'HK', name: 'Гонконг' },
  { code: 'HN', name: 'Гондурас' },
  { code: 'HR', name: 'Хорватия' },
  { code: 'HT', name: 'Гаити' },
  { code: 'HU', name: 'Венгрия' },
  { code: 'ID', name: 'Индонезия' },
  { code: 'IE', name: 'Ирландия' },
  { code: 'IL', name: 'Израиль' },
  { code: 'IN', name: 'Индия' },
  { code: 'IQ', name: 'Ирак' },
  { code: 'IR', name: 'Иран' },
  { code: 'IS', name: 'Исландия' },
  { code: 'IT', name: 'Италия' },
  { code: 'JM', name: 'Ямайка' },
  { code: 'JO', name: 'Иордания' },
  { code: 'JP', name: 'Япония' },
  { code: 'KE', name: 'Кения' },
  { code: 'KG', name: 'Киргизия' },
  { code: 'KH', name: 'Камбоджа' },
  { code: 'KI', name: 'Кирибати' },
  { code: 'KM', name: 'Коморы' },
  { code: 'KN', name: 'Сент-Китс и Невис' },
  { code: 'KP', name: 'КНДР' },
  { code: 'KR', name: 'Южная Корея' },
  { code: 'KW', name: 'Кувейт' },
  { code: 'KZ', name: 'Казахстан' },
  { code: 'LA', name: 'Лаос' },
  { code: 'LB', name: 'Ливан' },
  { code: 'LC', name: 'Сент-Люсия' },
  { code: 'LI', name: 'Лихтенштейн' },
  { code: 'LK', name: 'Шри-Ланка' },
  { code: 'LR', name: 'Либерия' },
  { code: 'LS', name: 'Лесото' },
  { code: 'LT', name: 'Литва' },
  { code: 'LU', name: 'Люксембург' },
  { code: 'LV', name: 'Латвия' },
  { code: 'LY', name: 'Ливия' },
  { code: 'MA', name: 'Марокко' },
  { code: 'MC', name: 'Монако' },
  { code: 'MD', name: 'Молдова' },
  { code: 'ME', name: 'Черногория' },
  { code: 'MG', name: 'Мадагаскар' },
  { code: 'MH', name: 'Маршалловы Острова' },
  { code: 'MK', name: 'Северная Македония' },
  { code: 'ML', name: 'Мали' },
  { code: 'MM', name: 'Мьянма' },
  { code: 'MN', name: 'Монголия' },
  { code: 'MO', name: 'Макао' },
  { code: 'MR', name: 'Мавритания' },
  { code: 'MT', name: 'Мальта' },
  { code: 'MU', name: 'Маврикий' },
  { code: 'MV', name: 'Мальдивы' },
  { code: 'MW', name: 'Малави' },
  { code: 'MX', name: 'Мексика' },
  { code: 'MY', name: 'Малайзия' },
  { code: 'MZ', name: 'Мозамбик' },
  { code: 'NA', name: 'Намибия' },
  { code: 'NE', name: 'Нигер' },
  { code: 'NG', name: 'Нигерия' },
  { code: 'NI', name: 'Никарагуа' },
  { code: 'NL', name: 'Нидерланды' },
  { code: 'NO', name: 'Норвегия' },
  { code: 'NP', name: 'Непал' },
  { code: 'NR', name: 'Науру' },
  { code: 'NZ', name: 'Новая Зеландия' },
  { code: 'OM', name: 'Оман' },
  { code: 'PA', name: 'Панама' },
  { code: 'PE', name: 'Перу' },
  { code: 'PG', name: 'Папуа — Новая Гвинея' },
  { code: 'PH', name: 'Филиппины' },
  { code: 'PK', name: 'Пакистан' },
  { code: 'PL', name: 'Польша' },
  { code: 'PS', name: 'Палестина' },
  { code: 'PT', name: 'Португалия' },
  { code: 'PW', name: 'Палау' },
  { code: 'PY', name: 'Парагвай' },
  { code: 'QA', name: 'Катар' },
  { code: 'RO', name: 'Румыния' },
  { code: 'RS', name: 'Сербия' },
  { code: 'RU', name: 'Россия' },
  { code: 'RW', name: 'Руанда' },
  { code: 'SA', name: 'Саудовская Аравия' },
  { code: 'SB', name: 'Соломоновы Острова' },
  { code: 'SC', name: 'Сейшелы' },
  { code: 'SD', name: 'Судан' },
  { code: 'SE', name: 'Швеция' },
  { code: 'SG', name: 'Сингапур' },
  { code: 'SI', name: 'Словения' },
  { code: 'SK', name: 'Словакия' },
  { code: 'SL', name: 'Сьерра-Леоне' },
  { code: 'SM', name: 'Сан-Марино' },
  { code: 'SN', name: 'Сенегал' },
  { code: 'SO', name: 'Сомали' },
  { code: 'SR', name: 'Суринам' },
  { code: 'SS', name: 'Южный Судан' },
  { code: 'ST', name: 'Сан-Томе и Принсипи' },
  { code: 'SV', name: 'Сальвадор' },
  { code: 'SY', name: 'Сирия' },
  { code: 'SZ', name: 'Эсватини' },
  { code: 'TD', name: 'Чад' },
  { code: 'TG', name: 'Того' },
  { code: 'TH', name: 'Таиланд' },
  { code: 'TJ', name: 'Таджикистан' },
  { code: 'TL', name: 'Тимор-Лесте' },
  { code: 'TM', name: 'Туркменистан' },
  { code: 'TN', name: 'Тунис' },
  { code: 'TO', name: 'Тонга' },
  { code: 'TR', name: 'Турция' },
  { code: 'TT', name: 'Тринидад и Тобаго' },
  { code: 'TV', name: 'Тувалу' },
  { code: 'TW', name: 'Тайвань' },
  { code: 'TZ', name: 'Танзания' },
  { code: 'UA', name: 'Украина' },
  { code: 'UG', name: 'Уганда' },
  { code: 'US', name: 'США' },
  { code: 'UY', name: 'Уругвай' },
  { code: 'UZ', name: 'Узбекистан' },
  { code: 'VA', name: 'Ватикан' },
  { code: 'VC', name: 'Сент-Винсент и Гренадины' },
  { code: 'VE', name: 'Венесуэла' },
  { code: 'VN', name: 'Вьетнам' },
  { code: 'VU', name: 'Вануату' },
  { code: 'WS', name: 'Самоа' },
  { code: 'YE', name: 'Йемен' },
  { code: 'ZA', name: 'ЮАР' },
  { code: 'ZM', name: 'Замбия' },
  { code: 'ZW', name: 'Зимбабве' },
];

export const COUNTRY_CODES = new Set(COUNTRIES.map((c) => c.code));

/** Проверяет ISO 3166-1 alpha-2. Регистронезависимо. */
export function isValidCountryCode(code: unknown): code is string {
  return typeof code === 'string' && /^[A-Z]{2}$/.test(code) && COUNTRY_CODES.has(code);
}
